//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comdeeds.QueryNameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asic.gov.au/wsdl/name/availability/external/v2", ConfigurationName="QueryNameService.ExternalQueryNameAvailability")]
    public interface ExternalQueryNameAvailability {
        
        // CODEGEN: Generating message contract since the operation externalQueryNameAvailability is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        comdeeds.QueryNameService.reply externalQueryNameAvailability(comdeeds.QueryNameService.request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<comdeeds.QueryNameService.reply> externalQueryNameAvailabilityAsync(comdeeds.QueryNameService.request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:v2.external.query.name.availability.asic.gov.au")]
    public partial class queryNameAvailabilityRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private businessDocumentHeaderType businessDocumentHeaderField;
        
        private queryNniNameType businessDocumentBodyField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="uri:business.document.header.types.asic.gov.au", Order=0)]
        public businessDocumentHeaderType businessDocumentHeader {
            get {
                return this.businessDocumentHeaderField;
            }
            set {
                this.businessDocumentHeaderField = value;
                this.RaisePropertyChanged("businessDocumentHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public queryNniNameType businessDocumentBody {
            get {
                return this.businessDocumentBodyField;
            }
            set {
                this.businessDocumentBodyField = value;
                this.RaisePropertyChanged("businessDocumentBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d", DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au")]
    public partial class businessDocumentHeaderType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageTypeField;
        
        private string messageReferenceNumberField;
        
        private string asicReferenceNumberField;
        
        private long messageVersionField;
        
        private string senderIdField;
        
        private string senderTypeField;
        
        private softwareInformationType softwareInformationField;
        
        private messageTimestampType[] messageTimestampsField;
        
        private messageEventType[] messageEventsField;
        
        private genericResultType resultField;
        
        private attachmentType[] attachmentsField;
        
        private receiptType receiptField;
        
        private string asicTransactionNumberField;
        
        private string transactionReferenceNumberField;
        
        private businessDocumentHeaderTypeProcessMode processModeField;
        
        private bool processModeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string messageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("messageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string messageReferenceNumber {
            get {
                return this.messageReferenceNumberField;
            }
            set {
                this.messageReferenceNumberField = value;
                this.RaisePropertyChanged("messageReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string asicReferenceNumber {
            get {
                return this.asicReferenceNumberField;
            }
            set {
                this.asicReferenceNumberField = value;
                this.RaisePropertyChanged("asicReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long messageVersion {
            get {
                return this.messageVersionField;
            }
            set {
                this.messageVersionField = value;
                this.RaisePropertyChanged("messageVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string senderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("senderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string senderType {
            get {
                return this.senderTypeField;
            }
            set {
                this.senderTypeField = value;
                this.RaisePropertyChanged("senderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public softwareInformationType softwareInformation {
            get {
                return this.softwareInformationField;
            }
            set {
                this.softwareInformationField = value;
                this.RaisePropertyChanged("softwareInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messageTimestamp", IsNullable=false)]
        public messageTimestampType[] messageTimestamps {
            get {
                return this.messageTimestampsField;
            }
            set {
                this.messageTimestampsField = value;
                this.RaisePropertyChanged("messageTimestamps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("messageEvent", IsNullable=false)]
        public messageEventType[] messageEvents {
            get {
                return this.messageEventsField;
            }
            set {
                this.messageEventsField = value;
                this.RaisePropertyChanged("messageEvents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public genericResultType result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("attachment", IsNullable=false)]
        public attachmentType[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public receiptType receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
                this.RaisePropertyChanged("receipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string asicTransactionNumber {
            get {
                return this.asicTransactionNumberField;
            }
            set {
                this.asicTransactionNumberField = value;
                this.RaisePropertyChanged("asicTransactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string transactionReferenceNumber {
            get {
                return this.transactionReferenceNumberField;
            }
            set {
                this.transactionReferenceNumberField = value;
                this.RaisePropertyChanged("transactionReferenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public businessDocumentHeaderTypeProcessMode processMode {
            get {
                return this.processModeField;
            }
            set {
                this.processModeField = value;
                this.RaisePropertyChanged("processMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool processModeSpecified {
            get {
                return this.processModeFieldSpecified;
            }
            set {
                this.processModeFieldSpecified = value;
                this.RaisePropertyChanged("processModeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au")]
    public partial class softwareInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string organisationalNameField;
        
        private string productNameField;
        
        private string productVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string organisationalName {
            get {
                return this.organisationalNameField;
            }
            set {
                this.organisationalNameField = value;
                this.RaisePropertyChanged("organisationalName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string productVersion {
            get {
                return this.productVersionField;
            }
            set {
                this.productVersionField = value;
                this.RaisePropertyChanged("productVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au")]
    public partial class objectionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionsField;
        
        private string[] contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
                this.RaisePropertyChanged("descriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("line", IsNullable=false)]
        public string[] context {
            get {
                return this.contextField;
            }
            set {
                this.contextField = value;
                this.RaisePropertyChanged("context");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au")]
    public partial class nameAvailabilityResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private nameAvailabilityResponseTypeCode codeField;
        
        private string shortDescriptionField;
        
        private string longDescriptionField;
        
        private objectionType[] objectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public nameAvailabilityResponseTypeCode code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string shortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
                this.RaisePropertyChanged("shortDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string longDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
                this.RaisePropertyChanged("longDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objection", Order=3)]
        public objectionType[] objection {
            get {
                return this.objectionField;
            }
            set {
                this.objectionField = value;
                this.RaisePropertyChanged("objection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri:types.asic.gov.au")]
    public enum nameAvailabilityResponseTypeCode {
        
        /// <remarks/>
        Available,
        
        /// <remarks/>
        Unavailable,
        
        /// <remarks/>
        SubjectToNamesDetermination,
        
        /// <remarks/>
        UnderTransfer,
        
        /// <remarks/>
        Identical,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:v2.external.query.name.availability.asic.gov.au")]
    public partial class queryNameAvailabilityReplyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private businessDocumentHeaderType businessDocumentHeaderField;
        
        private nameAvailabilityResponseType businessDocumentBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="uri:business.document.header.types.asic.gov.au", Order=0)]
        public businessDocumentHeaderType businessDocumentHeader {
            get {
                return this.businessDocumentHeaderField;
            }
            set {
                this.businessDocumentHeaderField = value;
                this.RaisePropertyChanged("businessDocumentHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public nameAvailabilityResponseType businessDocumentBody {
            get {
                return this.businessDocumentBodyField;
            }
            set {
                this.businessDocumentBodyField = value;
                this.RaisePropertyChanged("businessDocumentBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:nni.types.asic.gov.au")]
    public partial class queryNniNameType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string proposedNameField;
        
        private bool itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        private queryNniNameTypeProprietor proprietorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string proposedName {
            get {
                return this.proposedNameField;
            }
            set {
                this.proposedNameField = value;
                this.RaisePropertyChanged("proposedName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bnNameAvailabilityCheck", typeof(bool), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("companyNameAvailabilityCheck", typeof(bool), Order=1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public bool Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public queryNniNameTypeProprietor proprietor {
            get {
                return this.proprietorField;
            }
            set {
                this.proprietorField = value;
                this.RaisePropertyChanged("proprietor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:nni.types.asic.gov.au", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        bnNameAvailabilityCheck,
        
        /// <remarks/>
        companyNameAvailabilityCheck,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri:nni.types.asic.gov.au")]
    public partial class queryNniNameTypeProprietor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType4 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("proprietorAbn", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("proprietorAcn", typeof(string), DataType="positiveInteger", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:nni.types.asic.gov.au", IncludeInSchema=false)]
    public enum ItemChoiceType4 {
        
        /// <remarks/>
        proprietorAbn,
        
        /// <remarks/>
        proprietorAcn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:fss.types.asic.gov.au")]
    public partial class asicPaymentDetailsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string abnField;
        
        private string titleForPaymentField;
        
        private string addressForPaymentField;
        
        private string phoneForQueriesField;
        
        private string barcodeField;
        
        private asicPaymentDetailsTypeBpay bpayField;
        
        private asicPaymentDetailsTypePostBillpay postBillpayField;
        
        private string eftReferenceNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abn {
            get {
                return this.abnField;
            }
            set {
                this.abnField = value;
                this.RaisePropertyChanged("abn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string titleForPayment {
            get {
                return this.titleForPaymentField;
            }
            set {
                this.titleForPaymentField = value;
                this.RaisePropertyChanged("titleForPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string addressForPayment {
            get {
                return this.addressForPaymentField;
            }
            set {
                this.addressForPaymentField = value;
                this.RaisePropertyChanged("addressForPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string phoneForQueries {
            get {
                return this.phoneForQueriesField;
            }
            set {
                this.phoneForQueriesField = value;
                this.RaisePropertyChanged("phoneForQueries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public asicPaymentDetailsTypeBpay bpay {
            get {
                return this.bpayField;
            }
            set {
                this.bpayField = value;
                this.RaisePropertyChanged("bpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public asicPaymentDetailsTypePostBillpay postBillpay {
            get {
                return this.postBillpayField;
            }
            set {
                this.postBillpayField = value;
                this.RaisePropertyChanged("postBillpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=7)]
        public string eftReferenceNumber {
            get {
                return this.eftReferenceNumberField;
            }
            set {
                this.eftReferenceNumberField = value;
                this.RaisePropertyChanged("eftReferenceNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri:fss.types.asic.gov.au")]
    public partial class asicPaymentDetailsTypeBpay : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billerCodeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string billerCode {
            get {
                return this.billerCodeField;
            }
            set {
                this.billerCodeField = value;
                this.RaisePropertyChanged("billerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("ref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri:fss.types.asic.gov.au")]
    public partial class asicPaymentDetailsTypePostBillpay : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billpayCodeField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string billpayCode {
            get {
                return this.billpayCodeField;
            }
            set {
                this.billpayCodeField = value;
                this.RaisePropertyChanged("billpayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
                this.RaisePropertyChanged("ref");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:fss.types.asic.gov.au")]
    public partial class transactionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private fssAccountType reportingPartyField;
        
        private System.DateTime dateField;
        
        private string codeField;
        
        private string descriptionLine1Field;
        
        private string descriptionLine2Field;
        
        private string referenceField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public fssAccountType reportingParty {
            get {
                return this.reportingPartyField;
            }
            set {
                this.reportingPartyField = value;
                this.RaisePropertyChanged("reportingParty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descriptionLine1 {
            get {
                return this.descriptionLine1Field;
            }
            set {
                this.descriptionLine1Field = value;
                this.RaisePropertyChanged("descriptionLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descriptionLine2 {
            get {
                return this.descriptionLine2Field;
            }
            set {
                this.descriptionLine2Field = value;
                this.RaisePropertyChanged("descriptionLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:fss.types.asic.gov.au")]
    public partial class fssAccountType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string asicTypeField;
        
        private string ledgerNumberField;
        
        private string asicIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string asicType {
            get {
                return this.asicTypeField;
            }
            set {
                this.asicTypeField = value;
                this.RaisePropertyChanged("asicType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=1)]
        public string ledgerNumber {
            get {
                return this.ledgerNumberField;
            }
            set {
                this.ledgerNumberField = value;
                this.RaisePropertyChanged("ledgerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=2)]
        public string asicIdentifier {
            get {
                return this.asicIdentifierField;
            }
            set {
                this.asicIdentifierField = value;
                this.RaisePropertyChanged("asicIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au")]
    public partial class streetType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string streetNumberField;
        
        private string streetNameField;
        
        private string streetType1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string streetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
                this.RaisePropertyChanged("streetNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string streetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("streetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("streetType", Order=2)]
        public string streetType1 {
            get {
                return this.streetType1Field;
            }
            set {
                this.streetType1Field = value;
                this.RaisePropertyChanged("streetType1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au")]
    public partial class addressType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private addressTypeType typeField;
        
        private bool typeFieldSpecified;
        
        private string careOfField;
        
        private string[] addressLineField;
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        private string dPIDField;
        
        private string ascotIdField;
        
        private bool isForeignField;
        
        private bool isForeignFieldSpecified;
        
        private bool isPoBoxField;
        
        private bool isPoBoxFieldSpecified;
        
        private streetType streetField;
        
        private string localityField;
        
        private string postCodeField;
        
        private stateTerritoryCodeType stateField;
        
        private bool stateFieldSpecified;
        
        private string sequenceField;
        
        private bool overrideField;
        
        private bool overrideFieldSpecified;
        
        private addressTypeAction actionField;
        
        private bool actionFieldSpecified;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private string documentNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public addressTypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string careOf {
            get {
                return this.careOfField;
            }
            set {
                this.careOfField = value;
                this.RaisePropertyChanged("careOf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addressLine", Order=2)]
        public string[] addressLine {
            get {
                return this.addressLineField;
            }
            set {
                this.addressLineField = value;
                this.RaisePropertyChanged("addressLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("country", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("iso3166CountryCode", typeof(string), Order=3)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DPID {
            get {
                return this.dPIDField;
            }
            set {
                this.dPIDField = value;
                this.RaisePropertyChanged("DPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string ascotId {
            get {
                return this.ascotIdField;
            }
            set {
                this.ascotIdField = value;
                this.RaisePropertyChanged("ascotId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool isForeign {
            get {
                return this.isForeignField;
            }
            set {
                this.isForeignField = value;
                this.RaisePropertyChanged("isForeign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isForeignSpecified {
            get {
                return this.isForeignFieldSpecified;
            }
            set {
                this.isForeignFieldSpecified = value;
                this.RaisePropertyChanged("isForeignSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool isPoBox {
            get {
                return this.isPoBoxField;
            }
            set {
                this.isPoBoxField = value;
                this.RaisePropertyChanged("isPoBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPoBoxSpecified {
            get {
                return this.isPoBoxFieldSpecified;
            }
            set {
                this.isPoBoxFieldSpecified = value;
                this.RaisePropertyChanged("isPoBoxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public streetType street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("locality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string postCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("postCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public stateTerritoryCodeType state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("stateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=13)]
        public string sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool @override {
            get {
                return this.overrideField;
            }
            set {
                this.overrideField = value;
                this.RaisePropertyChanged("override");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overrideSpecified {
            get {
                return this.overrideFieldSpecified;
            }
            set {
                this.overrideFieldSpecified = value;
                this.RaisePropertyChanged("overrideSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public addressTypeAction action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionSpecified {
            get {
                return this.actionFieldSpecified;
            }
            set {
                this.actionFieldSpecified = value;
                this.RaisePropertyChanged("actionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
                this.RaisePropertyChanged("startDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
                this.RaisePropertyChanged("endDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au")]
    public enum addressTypeType {
        
        /// <remarks/>
        RG,
        
        /// <remarks/>
        RP,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        GC,
        
        /// <remarks/>
        GD,
        
        /// <remarks/>
        GE,
        
        /// <remarks/>
        GL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        country,
        
        /// <remarks/>
        iso3166CountryCode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:types.asic.gov.au")]
    public enum stateTerritoryCodeType {
        
        /// <remarks/>
        ACT,
        
        /// <remarks/>
        NSW,
        
        /// <remarks/>
        NT,
        
        /// <remarks/>
        QLD,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        TAS,
        
        /// <remarks/>
        WA,
        
        /// <remarks/>
        VIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri:types.asic.gov.au")]
    public enum addressTypeAction {
        
        /// <remarks/>
        ADD,
        
        /// <remarks/>
        REMOVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:fss.types.asic.gov.au")]
    public partial class debtorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private fssAccountType accountField;
        
        private string nameField;
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private addressType addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public fssAccountType account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("abn", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("abnReferenceNumber", typeof(string), DataType="positiveInteger", Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public addressType address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:fss.types.asic.gov.au", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        abn,
        
        /// <remarks/>
        abnReferenceNumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:fss.types.asic.gov.au")]
    public partial class receiptType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private debtorType debtorField;
        
        private System.DateTime dateIssuedField;
        
        private transactionType[] transactionField;
        
        private decimal totalField;
        
        private decimal totalDueField;
        
        private System.DateTime dateDueField;
        
        private bool dateDueFieldSpecified;
        
        private asicPaymentDetailsType asicPaymentDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public debtorType debtor {
            get {
                return this.debtorField;
            }
            set {
                this.debtorField = value;
                this.RaisePropertyChanged("debtor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime dateIssued {
            get {
                return this.dateIssuedField;
            }
            set {
                this.dateIssuedField = value;
                this.RaisePropertyChanged("dateIssued");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction", Order=2)]
        public transactionType[] transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
                this.RaisePropertyChanged("transaction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal totalDue {
            get {
                return this.totalDueField;
            }
            set {
                this.totalDueField = value;
                this.RaisePropertyChanged("totalDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime dateDue {
            get {
                return this.dateDueField;
            }
            set {
                this.dateDueField = value;
                this.RaisePropertyChanged("dateDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateDueSpecified {
            get {
                return this.dateDueFieldSpecified;
            }
            set {
                this.dateDueFieldSpecified = value;
                this.RaisePropertyChanged("dateDueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public asicPaymentDetailsType asicPaymentDetails {
            get {
                return this.asicPaymentDetailsField;
            }
            set {
                this.asicPaymentDetailsField = value;
                this.RaisePropertyChanged("asicPaymentDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au")]
    public partial class attachmentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentTypeField;
        
        private byte[] binaryObjectField;
        
        private string documentNumberField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryObject {
            get {
                return this.binaryObjectField;
            }
            set {
                this.binaryObjectField = value;
                this.RaisePropertyChanged("binaryObject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=5)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au")]
    public partial class genericResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accepted", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("delayed", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("fault", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("rejected", typeof(bool), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public bool Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        accepted,
        
        /// <remarks/>
        delayed,
        
        /// <remarks/>
        fault,
        
        /// <remarks/>
        rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au")]
    public partial class messageEventType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string serverityCodeField;
        
        private string descriptionField;
        
        private string locationPathField;
        
        private string[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serverityCode {
            get {
                return this.serverityCodeField;
            }
            set {
                this.serverityCodeField = value;
                this.RaisePropertyChanged("serverityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string locationPath {
            get {
                return this.locationPathField;
            }
            set {
                this.locationPathField = value;
                this.RaisePropertyChanged("locationPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Order=4)]
        public string[] details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="uri:business.document.header.types.asic.gov.au")]
    public partial class messageTimestampType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timestampField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="uri:business.document.header.types.asic.gov.au")]
    public enum businessDocumentHeaderTypeProcessMode {
        
        /// <remarks/>
        VALIDATE,
        
        /// <remarks/>
        PROCESS,
        
        /// <remarks/>
        PEND,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="request", Namespace="uri:v2.external.query.name.availability.asic.gov.au", Order=0)]
        public comdeeds.QueryNameService.queryNameAvailabilityRequestType request1;
        
        public request() {
        }
        
        public request(comdeeds.QueryNameService.queryNameAvailabilityRequestType request1) {
            this.request1 = request1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class reply {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="reply", Namespace="uri:v2.external.query.name.availability.asic.gov.au", Order=0)]
        public comdeeds.QueryNameService.queryNameAvailabilityReplyType reply1;
        
        public reply() {
        }
        
        public reply(comdeeds.QueryNameService.queryNameAvailabilityReplyType reply1) {
            this.reply1 = reply1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExternalQueryNameAvailabilityChannel : comdeeds.QueryNameService.ExternalQueryNameAvailability, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExternalQueryNameAvailabilityClient : System.ServiceModel.ClientBase<comdeeds.QueryNameService.ExternalQueryNameAvailability>, comdeeds.QueryNameService.ExternalQueryNameAvailability {
        
        public ExternalQueryNameAvailabilityClient() {
        }
        
        public ExternalQueryNameAvailabilityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExternalQueryNameAvailabilityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalQueryNameAvailabilityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExternalQueryNameAvailabilityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        comdeeds.QueryNameService.reply comdeeds.QueryNameService.ExternalQueryNameAvailability.externalQueryNameAvailability(comdeeds.QueryNameService.request request) {
            return base.Channel.externalQueryNameAvailability(request);
        }
        
        public comdeeds.QueryNameService.queryNameAvailabilityReplyType externalQueryNameAvailability(comdeeds.QueryNameService.queryNameAvailabilityRequestType request1) {
            comdeeds.QueryNameService.request inValue = new comdeeds.QueryNameService.request();
            inValue.request1 = request1;
            comdeeds.QueryNameService.reply retVal = ((comdeeds.QueryNameService.ExternalQueryNameAvailability)(this)).externalQueryNameAvailability(inValue);
            return retVal.reply1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<comdeeds.QueryNameService.reply> comdeeds.QueryNameService.ExternalQueryNameAvailability.externalQueryNameAvailabilityAsync(comdeeds.QueryNameService.request request) {
            return base.Channel.externalQueryNameAvailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<comdeeds.QueryNameService.reply> externalQueryNameAvailabilityAsync(comdeeds.QueryNameService.queryNameAvailabilityRequestType request1) {
            comdeeds.QueryNameService.request inValue = new comdeeds.QueryNameService.request();
            inValue.request1 = request1;
            return ((comdeeds.QueryNameService.ExternalQueryNameAvailability)(this)).externalQueryNameAvailabilityAsync(inValue);
        }
    }
}
